# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iMessageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMessageDemo

end

target 'iMessageExtensionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMessageExtensionDemo
  pod 'SwiftMessages/AppExtension', :path => "../"

end
