target 'Demo' do
    use_frameworks!
    workspace 'Demo.xcworkspace'
    xcodeproj 'Demo.xcodeproj'
    pod 'SwiftMessages/App', :path => '../'
    pod 'SwiftMessages/Segues', :path => '../'
end

#target 'iMessageDemo' do
#    use_frameworks!
#    workspace 'Demo.xcworkspace'
#    xcodeproj 'Demo.xcodeproj'
#    pod 'SwiftMessages/AppExtension', :path => '../'
#end
